services:
  - type: web
    name: maim-gmail-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "[6375918223]"
      - key: PORT
        value: 10000
      - key: AUTO_PAYMENT_ENABLED
        value: "True"
      - key: FAKE_USER_ENABLED
        value: "True"
